#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'

bundle_data = {
  :"vim-ruby" => %w[vim-ruby],
  :"vim-scripts" => %w[AutoTag bash-support.vim jQuery matchit.zip Gist.vim IndexedSearch Color-Sampler-Pack ColorSchemeMenuMaker ScrollColors xterm16.vim netrw.vim ZoomWin],
  :tpope => %w[vim-cucumber vim-fugitive vim-git vim-haml vim-markdown vim-repeat vim-unimpaired vim-surround vim-vividchalk],
  :RubidiumStudios => %w[vim-rails],
  :rhysd => %w[vim-crystal],
  :jpalardy => %w[vim-slime],
  :lucapette => %w[vim-jquery-doc vim-ruby-doc],
  :astashov => %w[vim-ruby-debugger],
  :kchmck => %w[vim-coffee-script],
  :msanders => %w[snipmate.vim],
  :godlygeek => %w[tabular],
  :scrooloose => %w[nerdtree nerdcommenter snipmate-snippets],
  :jistr => %w[vim-nerdtree-tabs],
  :Xuyuanp => %w[nerdtree-git-plugin],
  :timcharper => %w[textile.vim],
  :mileszs => %w[ack.vim],
#  :suan => %w[vim-instant-markdown],
  :reinh => %w[vim-makegreen],
  :fatih => %w[vim-go],
  :lmeijvogel => %w[vim-yaml-helper],
#  :Shougo =>%w[neocomplete],
  :wincent => %w[Command-T],
  :w0rp => %w[ale],
  :"vim-airline" => %w[vim-airline vim-airline-themes],
#  :wakatime => %w[vim-wakatime],
#  :Yggdroot => %w[indentLine],

  # Colorschemes - from vimcolors.com
  :Addisonbean => %w[Vim-Xcode-Theme],
  :GertjanReynaert => %w[cobalt2-vim-theme],
  :YorickPeterse => %w[happy_hacking.vim],
  :albertocg => %w[contrastneed-theme],
  :atelierbram => %w[vim-colors_atelier-schemes vim-colors_duotones],
  :bounceme => %w[base.vim],
  :encody => %w[vim-colors],
  :gryftir => %w[gryffin],
  :josuegaleas => %w[jay],
  :lifepillar => %w[vim-solarized8],
  :marciomazza => %w[vim-brogrammer-theme],
  :marcopaganini => %w[termschool-vim-theme],
  :mkarmona => %w[colorsbox],
  :rakr => %w[vim-one],
  :roosta => %w[vim-srcery],
  :the31k => %w[vim-colors-tayra],
  :tyrannicaltoucan => %w[vim-deep-space],
  :wellsjo => %w[wellsokai.vim],
}

git_bundles = []
bundle_data.each do |author, scripts|
  scripts.each do |name|
    git_bundles << "git://github.com/#{author}/#{name}.git"
  end
end

def dos2unix?
  if defined?(@supported)
    @supported
  else
    @supported = system("which dos2unix >/dev/null")
  end
end

# Some people are dumb and use Windows line endings
def dos2unix(dir)
  return unless dos2unix?
  system "find #{dir} -type f -exec dos2unix -q -k {} \\;"
end

# Install pathogen if its missing
autoload_dir = File.join(File.dirname(__FILE__), "autoload")
FileUtils.mkdir_p(autoload_dir) unless File.directory?(autoload_dir)
`curl -so #{autoload_dir}/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim` if (!File.exists?(File.join(autoload_dir,'pathogen.vim')) or ARGV.include? '--force')

# Install the bundles
bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.rm_rf(bundles_dir) if File.directory?(bundles_dir)
FileUtils.mkdir_p(bundles_dir)
Dir.chdir(bundles_dir) do
  $stderr.puts "Downloading vim bundles"
  git_bundles.each do |url|
    dir = File.basename(url, '.git')
    label = "  [#{dir}]".ljust(18)
    $stderr.puts "#{label} -> #{url}"
    `git clone -q #{url} #{dir}`
    FileUtils.rm_rf(File.join(dir, ".git"))
    dos2unix dir
  end
end

# Special handling for Command-T
vim_version = (/.* ([\d]*\.[\d]*) \(.*/.match(`vim --version | head -n1`)[1] || 0).to_f
have_rvm = `rvm > /dev/null 2>&1` && $?.exitstatus == 0 && !!ENV['MY_RUBY_HOME'];
cmd = (have_rvm && vim_version < 8.1) ? "rvm system ruby extconf.rb" : "/usr/bin/env ruby extconf.rb"
Dir.chdir(File.join(bundles_dir,"Command-T","ruby/command-t/ext/command-t")) do
  system cmd
  system "make clean && make"
end
if have_rvm && vim_version >= 8.1
  dll = `find $MY_RUBY_HOME -name '*.dylib' -type f | head -n1`.chomp
  system 'sed -e \'s|^\( *\)set rubydll.*|\1set rubydll='+dll+'|\' -i "" '+File.realpath("#{ENV['HOME']}/.vimrc")
end


# Special handling for scrooloose's snippets -- need to move into a snippets subdirectory to work 
# currently disabled because of conflicts
#Dir.chdir(File.join(bundles_dir,"snipmate-snippets")) do
  #FileUtils.mkdir('snippets')
  #FileUtils.rm('Rakefile')
  #system 'find . \! -name snippets \! -name "." -maxdepth 1 -exec mv {} snippets \;'
#end

